default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sync_code_signing(type: "appstore")
    increment_build_number(xcodeproj: "surfmappers.xcodeproj")
    build_app(workspace: "surfmappers.xcworkspace", scheme: "surfmappers")
    upload_to_testflight
  end
end
